package com.ayantsoft.trmsv3_SOA.hibernate.pojo;
// Generated 23 Jun, 2017 5:01:16 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name = "bank", catalog = "ayant_trmsv2")
public class Bank implements java.io.Serializable {

	private Integer bankId;
	private String bankAccountNo;
	private String bankIfsc;
	private String bankName;
	private String bankBranch;
	private String bankAccountType;
	private int vendorId;

	public Bank() {
	}

	public Bank(int vendorId) {
		this.vendorId = vendorId;
	}

	public Bank(String bankAccountNo, String bankIfsc, String bankName, String bankBranch, String bankAccountType,
			int vendorId) {
		this.bankAccountNo = bankAccountNo;
		this.bankIfsc = bankIfsc;
		this.bankName = bankName;
		this.bankBranch = bankBranch;
		this.bankAccountType = bankAccountType;
		this.vendorId = vendorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bankId", unique = true, nullable = false)
	public Integer getBankId() {
		return this.bankId;
	}

	public void setBankId(Integer bankId) {
		this.bankId = bankId;
	}

	@Column(name = "bank_account_no", length = 100)
	public String getBankAccountNo() {
		return this.bankAccountNo;
	}

	public void setBankAccountNo(String bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}

	@Column(name = "bank_ifsc", length = 100)
	public String getBankIfsc() {
		return this.bankIfsc;
	}

	public void setBankIfsc(String bankIfsc) {
		this.bankIfsc = bankIfsc;
	}

	@Column(name = "bank_name", length = 100)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_branch", length = 200)
	public String getBankBranch() {
		return this.bankBranch;
	}

	public void setBankBranch(String bankBranch) {
		this.bankBranch = bankBranch;
	}

	@Column(name = "bank_account_type", length = 45)
	public String getBankAccountType() {
		return this.bankAccountType;
	}

	public void setBankAccountType(String bankAccountType) {
		this.bankAccountType = bankAccountType;
	}

	@Column(name = "vendor_id", nullable = false)
	public int getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(int vendorId) {
		this.vendorId = vendorId;
	}

}
