package com.ayantsoft.trmsv3_SOA.hibernate.pojo;
// Generated 23 Jun, 2017 5:01:16 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeeHasTaskId generated by hbm2java
 */
@Embeddable
public class EmployeeHasTaskId implements java.io.Serializable {

	private int employeeId;
	private int taskId;

	public EmployeeHasTaskId() {
	}

	public EmployeeHasTaskId(int employeeId, int taskId) {
		this.employeeId = employeeId;
		this.taskId = taskId;
	}

	@Column(name = "employee_id", nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "task_id", nullable = false)
	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeHasTaskId))
			return false;
		EmployeeHasTaskId castOther = (EmployeeHasTaskId) other;

		return (this.getEmployeeId() == castOther.getEmployeeId()) && (this.getTaskId() == castOther.getTaskId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmployeeId();
		result = 37 * result + this.getTaskId();
		return result;
	}

}
